FROM ubuntu
WORKDIR /app
COPY . .
SHELL ["/bin/bash", "-c"] 
RUN apt update
RUN apt install python3-pip -y  python3-venv -y 
RUN python3 -m venv .venv
RUN source .venv/bin/activate
RUN .venv/bin/pip3 install -r requirements.txt
ENTRYPOINT [ ".venv/bin/python3" ]
EXPOSE 8000
CMD ["web.py"]